insert into user_group (id, is_listed, name, url) values (1, true, 'Roberts and Sons', 'netlog.com/nibh/in/quis/justo/maecenas/rhoncus/aliquam.js');
insert into user_group (id, is_listed, name, url) values (2, true, 'Hickle LLC', 'prnewswire.com/nam/ultrices/libero/non/mattis/pulvinar.xml');
insert into user_group (id, is_listed, name, url) values (3, true, 'Waters, Lakin and Gutkowski', 'fotki.com/elementum/nullam/varius/nulla/facilisi/cras.html');
insert into user_group (id, is_listed, name, url) values (4, false, 'Bauch and Sons', 'apple.com/ac/leo/pellentesque.xml');
insert into user_group (id, is_listed, name, url) values (5, true, 'Zboncak and Sons', 'opensource.org/eu/felis.js');
insert into user_group (id, is_listed, name, url) values (6, false, 'Ledner, Lowe and MacGyver', 'printfriendly.com/volutpat/erat/quisque/erat/eros.js');
insert into user_group (id, is_listed, name, url) values (7, false, 'Yost, Stroman and King', 'google.com.br/erat.xml');
insert into user_group (id, is_listed, name, url) values (8, false, 'Rutherford and Sons', 'google.it/eleifend/quam.xml');
insert into user_group (id, is_listed, name, url) values (9, true, 'Kub LLC', 'unblog.fr/euismod/scelerisque/quam/turpis/adipiscing/lorem.jpg');
insert into user_group (id, is_listed, name, url) values (10, false, 'Doyle-Ullrich', 'comcast.net/in/leo/maecenas/pulvinar.json');
insert into user_group (id, is_listed, name, url) values (11, true, 'Johnston, Romaguera and Yundt', 'woothemes.com/consectetuer.xml');
insert into user_group (id, is_listed, name, url) values (12, true, 'Cremin, Schoen and Oberbrunner', 'bandcamp.com/amet/consectetuer/adipiscing/elit/proin/interdum.aspx');
insert into user_group (id, is_listed, name, url) values (13, true, 'Kuhlman, Abbott and Becker', 'ebay.com/in/felis/donec/semper/sapien.html');
insert into user_group (id, is_listed, name, url) values (14, false, 'Effertz and Sons', 'latimes.com/odio/curabitur/convallis/duis.js');
insert into user_group (id, is_listed, name, url) values (15, true, 'Thiel-Heller', 'ifeng.com/aliquam.json');
insert into user_group (id, is_listed, name, url) values (16, true, 'Harris LLC', 'independent.co.uk/vel/enim/sit.html');
insert into user_group (id, is_listed, name, url) values (17, true, 'Hilpert-Shanahan', 'cdc.gov/morbi.aspx');
insert into user_group (id, is_listed, name, url) values (18, true, 'Hand-Barton', 'ox.ac.uk/justo/aliquam/quis/turpis/eget.aspx');
insert into user_group (id, is_listed, name, url) values (19, true, 'Quitzon, McGlynn and Purdy', 'disqus.com/amet/sem/fusce/consequat/nulla/nisl.js');
insert into user_group (id, is_listed, name, url) values (20, true, 'Raynor, Smitham and Harris', 'trellian.com/suspendisse/accumsan/tortor/quis/turpis/sed.png');
insert into user_group (id, is_listed, name, url) values (21, false, 'Tromp, Hayes and Beatty', 'google.nl/ac/nulla/sed/vel/enim/sit/amet.aspx');
insert into user_group (id, is_listed, name, url) values (22, false, 'Willms, Muller and Ullrich', 'techcrunch.com/turpis/eget.png');
insert into user_group (id, is_listed, name, url) values (23, false, 'Gulgowski, Heidenreich and Blanda', 'instagram.com/sem/praesent/id.png');
insert into user_group (id, is_listed, name, url) values (24, true, 'Yost, Hermann and Yundt', 'vistaprint.com/orci.png');
insert into user_group (id, is_listed, name, url) values (25, true, 'Dietrich, Ondricka and Mayer', 'ycombinator.com/aliquam/augue/quam/sollicitudin/vitae/consectetuer/eget.html');
insert into user_group (id, is_listed, name, url) values (26, true, 'O''Kon, Frami and Daniel', '1688.com/pellentesque/eget/nunc/donec/quis.html');
insert into user_group (id, is_listed, name, url) values (27, false, 'Powlowski, Wilderman and Rosenbaum', 'senate.gov/hac/habitasse/platea/dictumst/etiam/faucibus.aspx');
insert into user_group (id, is_listed, name, url) values (28, true, 'Marquardt Group', 'hostgator.com/vestibulum/ante/ipsum.jsp');
insert into user_group (id, is_listed, name, url) values (29, true, 'Bartoletti, Schowalter and Vandervort', 'hud.gov/id/lobortis/convallis/tortor.json');
insert into user_group (id, is_listed, name, url) values (30, false, 'Schaefer, Satterfield and Medhurst', 'arizona.edu/purus/sit/amet/nulla.js');
insert into user_group (id, is_listed, name, url) values (31, false, 'Johnson LLC', 'liveinternet.ru/in/tempus/sit/amet.jsp');
insert into user_group (id, is_listed, name, url) values (32, false, 'Kuphal-King', 'quantcast.com/nulla.jsp');
insert into user_group (id, is_listed, name, url) values (33, false, 'Bahringer Group', 'elpais.com/libero/quis/orci/nullam.jsp');
insert into user_group (id, is_listed, name, url) values (34, true, 'Walker Group', 'guardian.co.uk/id/lobortis.js');
insert into user_group (id, is_listed, name, url) values (35, false, 'Friesen, Hayes and Lubowitz', 'reddit.com/scelerisque/quam/turpis/adipiscing.aspx');
insert into user_group (id, is_listed, name, url) values (36, false, 'Witting Group', 'newyorker.com/viverra/diam.png');
insert into user_group (id, is_listed, name, url) values (37, true, 'Watsica-Hessel', 'telegraph.co.uk/quisque/erat/eros/viverra.png');
insert into user_group (id, is_listed, name, url) values (38, false, 'Haag and Sons', 'com.com/duis.json');
insert into user_group (id, is_listed, name, url) values (39, true, 'MacGyver-Feest', 'taobao.com/risus/auctor/sed/tristique/in.jpg');
insert into user_group (id, is_listed, name, url) values (40, false, 'Schmidt, Hintz and Frami', 'scribd.com/risus/praesent.jsp');
insert into user_group (id, is_listed, name, url) values (41, true, 'Hoeger-D''Amore', '51.la/orci/vehicula/condimentum/curabitur/in/libero/ut.jpg');
insert into user_group (id, is_listed, name, url) values (42, true, 'Jerde Group', 'unicef.org/curae/mauris.html');
insert into user_group (id, is_listed, name, url) values (43, false, 'McLaughlin Group', 'live.com/morbi/non.js');
insert into user_group (id, is_listed, name, url) values (44, false, 'O''Kon, Flatley and Bechtelar', 'blogs.com/volutpat/dui.png');
insert into user_group (id, is_listed, name, url) values (45, true, 'D''Amore-Haag', 'weebly.com/erat/quisque/erat/eros/viverra/eget.png');
insert into user_group (id, is_listed, name, url) values (46, true, 'Oberbrunner, Rolfson and Goodwin', 'walmart.com/ridiculus/mus/etiam/vel/augue.js');
insert into user_group (id, is_listed, name, url) values (47, true, 'Hauck-Koepp', 'wunderground.com/faucibus/orci/luctus/et/ultrices/posuere/cubilia.png');
insert into user_group (id, is_listed, name, url) values (48, true, 'Bogisich Inc', 'mozilla.org/sapien/non/mi/integer/ac/neque.png');
insert into user_group (id, is_listed, name, url) values (49, false, 'Johnston-Goldner', 'java.com/platea/dictumst/maecenas/ut/massa/quis.json');
insert into user_group (id, is_listed, name, url) values (50, true, 'Schiller-Rogahn', 'yelp.com/nulla/ut/erat/id/mauris/vulputate/elementum.png');
insert into user_group (id, is_listed, name, url) values (51, true, 'Kub, Nienow and Rolfson', 'admin.ch/aenean/auctor/gravida/sem/praesent.json');
insert into user_group (id, is_listed, name, url) values (52, true, 'Waelchi, Hettinger and Torp', 'ft.com/nec/molestie.js');
insert into user_group (id, is_listed, name, url) values (53, true, 'Koch, Pfeffer and Rice', 'cbc.ca/ac/enim/in.xml');
insert into user_group (id, is_listed, name, url) values (54, true, 'Dickinson-Tillman', 'craigslist.org/nec/nisi/vulputate/nonummy.jpg');
insert into user_group (id, is_listed, name, url) values (55, true, 'Blick, Waters and Lindgren', 'google.com.au/aliquet/ultrices/erat.json');
insert into user_group (id, is_listed, name, url) values (56, false, 'Leannon, Mertz and Schiller', 'google.com.hk/sit/amet/consectetuer/adipiscing/elit/proin/interdum.json');
insert into user_group (id, is_listed, name, url) values (57, false, 'Cassin-Thiel', 'unc.edu/luctus/cum/sociis.jsp');
insert into user_group (id, is_listed, name, url) values (58, false, 'White LLC', 'goo.gl/nascetur/ridiculus/mus.js');
insert into user_group (id, is_listed, name, url) values (59, true, 'Kiehn-Schmeler', 'ca.gov/nunc/nisl/duis/bibendum/felis/sed/interdum.js');
insert into user_group (id, is_listed, name, url) values (60, false, 'Denesik, Buckridge and Jaskolski', 'chronoengine.com/adipiscing/lorem.aspx');
insert into user_group (id, is_listed, name, url) values (61, false, 'Graham, Hessel and Maggio', 'weather.com/diam/vitae.aspx');
insert into user_group (id, is_listed, name, url) values (62, true, 'Pollich LLC', 'yolasite.com/libero.jsp');
insert into user_group (id, is_listed, name, url) values (63, false, 'McKenzie and Sons', 'opera.com/duis/bibendum/felis.jsp');
insert into user_group (id, is_listed, name, url) values (64, false, 'Grady, Lindgren and Wisoky', 'clickbank.net/vel/est/donec.html');
insert into user_group (id, is_listed, name, url) values (65, false, 'Bergnaum, Becker and Feest', 'smugmug.com/magnis/dis/parturient/montes/nascetur/ridiculus.aspx');
insert into user_group (id, is_listed, name, url) values (66, true, 'Kemmer-Rippin', 'eepurl.com/eu/nibh/quisque/id/justo/sit/amet.json');
insert into user_group (id, is_listed, name, url) values (67, true, 'Breitenberg Inc', 'youku.com/eget/rutrum/at/lorem/integer/tincidunt.xml');
insert into user_group (id, is_listed, name, url) values (68, true, 'Gaylord, Anderson and Klein', 'archive.org/eget.jsp');
insert into user_group (id, is_listed, name, url) values (69, true, 'Fritsch Group', 'netscape.com/elementum/in/hac.jpg');
insert into user_group (id, is_listed, name, url) values (70, false, 'Hickle Inc', 'w3.org/vulputate/justo.js');
insert into user_group (id, is_listed, name, url) values (71, false, 'Wiza Group', '1und1.de/faucibus/orci/luctus/et/ultrices/posuere/cubilia.json');
insert into user_group (id, is_listed, name, url) values (72, false, 'Willms, Rosenbaum and Price', 'free.fr/elit/proin/interdum/mauris/non/ligula/pellentesque.png');
insert into user_group (id, is_listed, name, url) values (73, false, 'McDermott, Howell and Heathcote', 'dailymotion.com/purus.png');
insert into user_group (id, is_listed, name, url) values (74, true, 'Labadie, Berge and Jakubowski', 'cisco.com/non/velit/nec/nisi/vulputate.html');
insert into user_group (id, is_listed, name, url) values (75, false, 'Bahringer, Schultz and Lehner', 'engadget.com/diam.jpg');
insert into user_group (id, is_listed, name, url) values (76, true, 'Schuster, Kuhic and Metz', 'parallels.com/donec/semper/sapien/a/libero.png');
insert into user_group (id, is_listed, name, url) values (77, false, 'Turcotte, Bogisich and Leffler', 'csmonitor.com/ridiculus/mus/etiam.jsp');
insert into user_group (id, is_listed, name, url) values (78, false, 'Schimmel and Sons', 'nifty.com/lacinia/aenean.xml');
insert into user_group (id, is_listed, name, url) values (79, true, 'Jacobson, Gulgowski and Langworth', 'ebay.com/quis/augue/luctus/tincidunt/nulla.jpg');
insert into user_group (id, is_listed, name, url) values (80, true, 'Treutel-Jacobi', 'com.com/sed/augue/aliquam/erat/volutpat/in.html');
insert into user_group (id, is_listed, name, url) values (81, false, 'Russel, Blanda and Johns', '4shared.com/ut/massa/quis/augue.png');
insert into user_group (id, is_listed, name, url) values (82, false, 'Hintz LLC', 'baidu.com/sapien/iaculis.js');
insert into user_group (id, is_listed, name, url) values (83, false, 'Kuhlman, Rau and Gibson', 'gravatar.com/justo/in/hac/habitasse/platea/dictumst.js');
insert into user_group (id, is_listed, name, url) values (84, false, 'Crooks, Kuhic and Gaylord', 'mashable.com/aliquet/pulvinar/sed/nisl/nunc.jsp');
insert into user_group (id, is_listed, name, url) values (85, false, 'Bosco Group', 'barnesandnoble.com/et/magnis.jsp');
insert into user_group (id, is_listed, name, url) values (86, false, 'Schumm and Sons', 'purevolume.com/est/quam/pharetra/magna/ac.js');
insert into user_group (id, is_listed, name, url) values (87, true, 'Gerhold Inc', 'mashable.com/quisque/ut/erat/curabitur/gravida/nisi.xml');
insert into user_group (id, is_listed, name, url) values (88, true, 'Batz-Schneider', 'independent.co.uk/aliquet/at/feugiat/non/pretium/quis/lectus.html');
insert into user_group (id, is_listed, name, url) values (89, false, 'Schneider-Reilly', 'com.com/id/consequat/in/consequat/ut.jsp');
insert into user_group (id, is_listed, name, url) values (90, true, 'Goodwin Group', 'digg.com/metus.jsp');
insert into user_group (id, is_listed, name, url) values (91, false, 'Denesik Group', 'aboutads.info/tincidunt/ante/vel.jpg');
insert into user_group (id, is_listed, name, url) values (92, true, 'Smith, Quigley and Kemmer', 'wikispaces.com/vel/ipsum/praesent/blandit/lacinia/erat.jpg');
insert into user_group (id, is_listed, name, url) values (93, true, 'Will-Daniel', 'tripadvisor.com/massa/id/lobortis/convallis.xml');
insert into user_group (id, is_listed, name, url) values (94, false, 'Nicolas Group', 'telegraph.co.uk/cras/non/velit/nec/nisi/vulputate.jsp');
insert into user_group (id, is_listed, name, url) values (95, true, 'Shields LLC', 'rakuten.co.jp/nonummy/maecenas/tincidunt/lacus/at.xml');
insert into user_group (id, is_listed, name, url) values (96, true, 'Hansen Group', 'cnet.com/faucibus/orci/luctus.jsp');
insert into user_group (id, is_listed, name, url) values (97, true, 'Okuneva LLC', 'boston.com/vestibulum.jsp');
insert into user_group (id, is_listed, name, url) values (98, true, 'Beatty-Boehm', 'dropbox.com/dolor/morbi/vel/lectus.jsp');
insert into user_group (id, is_listed, name, url) values (99, false, 'Emard-Schimmel', 'google.ca/accumsan/felis/ut/at/dolor/quis.xml');
insert into user_group (id, is_listed, name, url) values (100, false, 'Schmitt LLC', 'google.cn/feugiat/non.png');