insert into company_location (company_id, location) values (5, 'Prroshyan');
insert into company_location (company_id, location) values (3, 'Jifarong');
insert into company_location (company_id, location) values (4, 'Rochefort');
insert into company_location (company_id, location) values (1, 'Norberg');
insert into company_location (company_id, location) values (2, 'Sukamulia');
insert into company_location (company_id, location) values (4, 'Alto Barinas');
insert into company_location (company_id, location) values (4, 'Tampere');
insert into company_location (company_id, location) values (5, 'Veliki Preslav');
insert into company_location (company_id, location) values (3, 'Ar Rumaythīyah');
insert into company_location (company_id, location) values (5, 'Bebedouro');