insert into job_skill (job_id, job_skill) values (1, 'Sony Vegas');
insert into job_skill (job_id, job_skill) values (9, 'KPI Implementation');
insert into job_skill (job_id, job_skill) values (7, 'Epidemiology');
insert into job_skill (job_id, job_skill) values (12, 'E-on Vue');
insert into job_skill (job_id, job_skill) values (8, 'PDF Creator');
insert into job_skill (job_id, job_skill) values (7, 'HTML');
insert into job_skill (job_id, job_skill) values (4, 'SAP Business ByDesign');
insert into job_skill (job_id, job_skill) values (8, 'Humanitarian Assistance');
insert into job_skill (job_id, job_skill) values (3, 'Luxury Lifestyle');
insert into job_skill (job_id, job_skill) values (8, 'VLR');
insert into job_skill (job_id, job_skill) values (6, 'Investment Banking');
insert into job_skill (job_id, job_skill) values (12, 'Avid DS Nitris');
insert into job_skill (job_id, job_skill) values (7, 'VDM');
insert into job_skill (job_id, job_skill) values (10, 'BMP design');
insert into job_skill (job_id, job_skill) values (10, 'Screening');
insert into job_skill (job_id, job_skill) values (14, 'Network Administration');
insert into job_skill (job_id, job_skill) values (11, 'WS-I');
insert into job_skill (job_id, job_skill) values (11, 'ePub');
insert into job_skill (job_id, job_skill) values (8, 'CTAs');
insert into job_skill (job_id, job_skill) values (12, 'Key Account Development');
insert into job_skill (job_id, job_skill) values (10, 'QC Tools');
insert into job_skill (job_id, job_skill) values (5, 'Office Equipment');
insert into job_skill (job_id, job_skill) values (8, 'AHA');
insert into job_skill (job_id, job_skill) values (14, 'Avid Newscutter');
insert into job_skill (job_id, job_skill) values (3, 'Airline Management');
insert into job_skill (job_id, job_skill) values (6, 'Fashion Jewelry');
insert into job_skill (job_id, job_skill) values (13, 'RMF');
insert into job_skill (job_id, job_skill) values (8, 'Mac OS X Server');
insert into job_skill (job_id, job_skill) values (3, 'JTest');
insert into job_skill (job_id, job_skill) values (2, 'Nightlife');
insert into job_skill (job_id, job_skill) values (11, 'PWM');
insert into job_skill (job_id, job_skill) values (9, 'MMO');
insert into job_skill (job_id, job_skill) values (2, 'Umbilicals');
insert into job_skill (job_id, job_skill) values (2, 'Theory');
insert into job_skill (job_id, job_skill) values (12, 'wxWidgets');
insert into job_skill (job_id, job_skill) values (10, 'Cell Biology');
insert into job_skill (job_id, job_skill) values (3, 'DDE');
insert into job_skill (job_id, job_skill) values (5, 'Threat &amp; Vulnerability Management');
insert into job_skill (job_id, job_skill) values (15, 'International Trade');
insert into job_skill (job_id, job_skill) values (4, 'Short Stories');
insert into job_skill (job_id, job_skill) values (8, 'FDR');
insert into job_skill (job_id, job_skill) values (4, 'Easily Adaptable');
insert into job_skill (job_id, job_skill) values (10, 'HR Metrics');
insert into job_skill (job_id, job_skill) values (12, 'Access Control');
insert into job_skill (job_id, job_skill) values (6, 'TMG');
insert into job_skill (job_id, job_skill) values (14, 'Yeast two-hybrid');
insert into job_skill (job_id, job_skill) values (10, 'Gynecologic Surgery');
insert into job_skill (job_id, job_skill) values (5, 'RMAN');
insert into job_skill (job_id, job_skill) values (2, 'Ubercart');
insert into job_skill (job_id, job_skill) values (9, 'IS-IS');