insert into user_skill (user_id, skill_definition) values (1, 'Business Object');
insert into user_skill (user_id, skill_definition) values (2, 'Yard Management');
insert into user_skill (user_id, skill_definition) values (3, 'Capital IQ');
insert into user_skill (user_id, skill_definition) values (4, 'PPBES');
insert into user_skill (user_id, skill_definition) values (5, 'Google Webmaster Tools');
insert into user_skill (user_id, skill_definition) values (6, 'MQL4');
insert into user_skill (user_id, skill_definition) values (7, 'Waste');
insert into user_skill (user_id, skill_definition) values (8, 'Quality Patient Care');
insert into user_skill (user_id, skill_definition) values (9, 'Visual Arts');
insert into user_skill (user_id, skill_definition) values (10, 'QARun');
insert into user_skill (user_id, skill_definition) values (11, 'Pulse Oximetry');
insert into user_skill (user_id, skill_definition) values (12, 'Sports Psychology');
insert into user_skill (user_id, skill_definition) values (13, 'ZeroMQ');
insert into user_skill (user_id, skill_definition) values (14, 'Security Clearance');
insert into user_skill (user_id, skill_definition) values (15, 'Easytrieve');
insert into user_skill (user_id, skill_definition) values (16, 'Lotus Domino');
insert into user_skill (user_id, skill_definition) values (17, 'Political Risk Analysis');
insert into user_skill (user_id, skill_definition) values (18, 'Islamic Finance');
insert into user_skill (user_id, skill_definition) values (19, 'Yacc');
insert into user_skill (user_id, skill_definition) values (20, 'GNU');
insert into user_skill (user_id, skill_definition) values (21, 'IAS 39');
insert into user_skill (user_id, skill_definition) values (22, 'Non-profit Administration');
insert into user_skill (user_id, skill_definition) values (23, 'PPPoA');
insert into user_skill (user_id, skill_definition) values (24, 'Early Intervention');
insert into user_skill (user_id, skill_definition) values (25, 'Private Equity');
insert into user_skill (user_id, skill_definition) values (26, 'TSS');
insert into user_skill (user_id, skill_definition) values (27, 'Business Development');
insert into user_skill (user_id, skill_definition) values (28, 'Lymphatic Drainage');
insert into user_skill (user_id, skill_definition) values (29, 'uDig');
insert into user_skill (user_id, skill_definition) values (30, 'Knowledge Base');
insert into user_skill (user_id, skill_definition) values (31, 'AHP');
insert into user_skill (user_id, skill_definition) values (32, 'PWE3');
insert into user_skill (user_id, skill_definition) values (33, 'Zendesk');
insert into user_skill (user_id, skill_definition) values (34, 'Oceanography');
insert into user_skill (user_id, skill_definition) values (35, 'Kronos Timekeeping');
insert into user_skill (user_id, skill_definition) values (36, 'VTR');
insert into user_skill (user_id, skill_definition) values (37, 'Nonprofits');
insert into user_skill (user_id, skill_definition) values (38, 'GPP');
insert into user_skill (user_id, skill_definition) values (39, 'PCR Primer Design');
insert into user_skill (user_id, skill_definition) values (40, 'ODIN');
insert into user_skill (user_id, skill_definition) values (41, 'Simulations');
insert into user_skill (user_id, skill_definition) values (42, 'HVAC Controls');
insert into user_skill (user_id, skill_definition) values (43, 'QEMU');
insert into user_skill (user_id, skill_definition) values (44, 'HFM');
insert into user_skill (user_id, skill_definition) values (45, 'Outsourcing Management');
insert into user_skill (user_id, skill_definition) values (46, 'iReport');
insert into user_skill (user_id, skill_definition) values (47, 'EPA');
insert into user_skill (user_id, skill_definition) values (48, 'HDSL');
insert into user_skill (user_id, skill_definition) values (49, 'Guitar');
insert into user_skill (user_id, skill_definition) values (50, 'KVM Switches');
insert into user_skill (user_id, skill_definition) values (51, 'Gutters');
insert into user_skill (user_id, skill_definition) values (52, 'Dell KACE');
insert into user_skill (user_id, skill_definition) values (53, 'Target Identification');
insert into user_skill (user_id, skill_definition) values (54, 'TCL');
insert into user_skill (user_id, skill_definition) values (55, 'Classical');
insert into user_skill (user_id, skill_definition) values (56, 'RMX');
insert into user_skill (user_id, skill_definition) values (57, 'Lawson HRIS');
insert into user_skill (user_id, skill_definition) values (58, 'JWICS');
insert into user_skill (user_id, skill_definition) values (59, 'CGI');
insert into user_skill (user_id, skill_definition) values (60, 'RTCP');
insert into user_skill (user_id, skill_definition) values (61, 'SAP SRM');
insert into user_skill (user_id, skill_definition) values (62, 'Offshore Outsourcing');
insert into user_skill (user_id, skill_definition) values (63, 'UIKit');
insert into user_skill (user_id, skill_definition) values (64, 'Fixed Income');
insert into user_skill (user_id, skill_definition) values (65, 'MRO Management');
insert into user_skill (user_id, skill_definition) values (66, 'RF');
insert into user_skill (user_id, skill_definition) values (67, 'Strategic Thinking');
insert into user_skill (user_id, skill_definition) values (68, 'UCINET');
insert into user_skill (user_id, skill_definition) values (69, 'Airframe');
insert into user_skill (user_id, skill_definition) values (70, 'Press Releases');
insert into user_skill (user_id, skill_definition) values (71, 'DVI');
insert into user_skill (user_id, skill_definition) values (72, 'DNA Extraction');
insert into user_skill (user_id, skill_definition) values (73, 'Nuclear Engineering');
insert into user_skill (user_id, skill_definition) values (74, 'Graphics');
insert into user_skill (user_id, skill_definition) values (75, 'Commercial Piloting');
insert into user_skill (user_id, skill_definition) values (76, 'BPEL');
insert into user_skill (user_id, skill_definition) values (77, 'Test Automation');
insert into user_skill (user_id, skill_definition) values (78, 'ABAP-OO');
insert into user_skill (user_id, skill_definition) values (79, 'DCP');
insert into user_skill (user_id, skill_definition) values (80, 'HDCAM');
insert into user_skill (user_id, skill_definition) values (81, 'SBMS');
insert into user_skill (user_id, skill_definition) values (82, 'SAP MDM');
insert into user_skill (user_id, skill_definition) values (83, 'Avid Media Composer');
insert into user_skill (user_id, skill_definition) values (84, 'Hazardous Waste Management');
insert into user_skill (user_id, skill_definition) values (85, 'Optical Tweezers');
insert into user_skill (user_id, skill_definition) values (86, 'Cd');
insert into user_skill (user_id, skill_definition) values (87, 'Outside Sales');
insert into user_skill (user_id, skill_definition) values (88, 'American Welding Society (AWS)');
insert into user_skill (user_id, skill_definition) values (89, 'LN');
insert into user_skill (user_id, skill_definition) values (90, 'OJEU');
insert into user_skill (user_id, skill_definition) values (91, 'Animal Husbandry');
insert into user_skill (user_id, skill_definition) values (92, 'User Experience Design');
insert into user_skill (user_id, skill_definition) values (93, 'HGV');
insert into user_skill (user_id, skill_definition) values (94, 'PTCRB');
insert into user_skill (user_id, skill_definition) values (95, 'MBD');
insert into user_skill (user_id, skill_definition) values (96, 'Power Plants');
insert into user_skill (user_id, skill_definition) values (97, 'RCP');
insert into user_skill (user_id, skill_definition) values (98, 'HNW');
insert into user_skill (user_id, skill_definition) values (99, 'Telecom BSS');
insert into user_skill (user_id, skill_definition) values (100, 'QA Engineering');
insert into user_skill (user_id, skill_definition) values (1, 'SQLite');
insert into user_skill (user_id, skill_definition) values (2, 'Nintex');
insert into user_skill (user_id, skill_definition) values (3, 'TFF');
insert into user_skill (user_id, skill_definition) values (4, 'Wholesale Purchasing');
insert into user_skill (user_id, skill_definition) values (5, 'Medical Terminology');
insert into user_skill (user_id, skill_definition) values (6, 'Ebooks');
insert into user_skill (user_id, skill_definition) values (7, 'Food Preparation');
insert into user_skill (user_id, skill_definition) values (8, 'PPTP');
insert into user_skill (user_id, skill_definition) values (9, 'Durable Goods');
insert into user_skill (user_id, skill_definition) values (10, 'VTL');
insert into user_skill (user_id, skill_definition) values (11, 'Flame AA');
insert into user_skill (user_id, skill_definition) values (12, 'Dance');
insert into user_skill (user_id, skill_definition) values (13, 'MDRs');
insert into user_skill (user_id, skill_definition) values (14, 'Phase II Environmental Site Assessments');
insert into user_skill (user_id, skill_definition) values (15, 'Time Management');
insert into user_skill (user_id, skill_definition) values (16, 'Registered Patent Attorney');
insert into user_skill (user_id, skill_definition) values (17, 'Eclipse CDT');
insert into user_skill (user_id, skill_definition) values (18, 'Azerbaijani');
insert into user_skill (user_id, skill_definition) values (19, 'UAV');
insert into user_skill (user_id, skill_definition) values (20, 'LNA');
insert into user_skill (user_id, skill_definition) values (21, 'Oracle HR');
insert into user_skill (user_id, skill_definition) values (22, 'Voiceovers');
insert into user_skill (user_id, skill_definition) values (23, 'Key Performance Indicators');
insert into user_skill (user_id, skill_definition) values (24, 'Vendor Relationship Management');
insert into user_skill (user_id, skill_definition) values (25, 'LCSH');
insert into user_skill (user_id, skill_definition) values (26, 'jQuery UI');
insert into user_skill (user_id, skill_definition) values (27, 'Bands');
insert into user_skill (user_id, skill_definition) values (28, 'LTV');
insert into user_skill (user_id, skill_definition) values (29, 'Botany');
insert into user_skill (user_id, skill_definition) values (30, 'zLinux');
insert into user_skill (user_id, skill_definition) values (31, 'Dyeing');
insert into user_skill (user_id, skill_definition) values (32, 'Inventory Management');
insert into user_skill (user_id, skill_definition) values (33, 'CMS-1500');
insert into user_skill (user_id, skill_definition) values (34, 'MSC Patran');
insert into user_skill (user_id, skill_definition) values (35, 'LLBLGen');
insert into user_skill (user_id, skill_definition) values (36, 'IGMP Snooping');
insert into user_skill (user_id, skill_definition) values (37, 'Cluster');
insert into user_skill (user_id, skill_definition) values (38, 'Fine Art Photography');
insert into user_skill (user_id, skill_definition) values (39, 'Subversion');
insert into user_skill (user_id, skill_definition) values (40, 'NXP');
insert into user_skill (user_id, skill_definition) values (41, 'IEEE 802.3');
insert into user_skill (user_id, skill_definition) values (42, 'ODS');
insert into user_skill (user_id, skill_definition) values (43, 'Crystal Reports');
insert into user_skill (user_id, skill_definition) values (44, 'BOSIET');
insert into user_skill (user_id, skill_definition) values (45, 'Sun Certified Java Programmer');
insert into user_skill (user_id, skill_definition) values (46, 'Prenuptial Agreements');
insert into user_skill (user_id, skill_definition) values (47, 'GCIA');
insert into user_skill (user_id, skill_definition) values (48, 'EWM');
insert into user_skill (user_id, skill_definition) values (49, 'PDF Creator');
insert into user_skill (user_id, skill_definition) values (50, 'Drilling');
insert into user_skill (user_id, skill_definition) values (51, 'OOS');
insert into user_skill (user_id, skill_definition) values (52, 'American Literature');
insert into user_skill (user_id, skill_definition) values (53, 'Trimble GPS');
insert into user_skill (user_id, skill_definition) values (54, 'Agilent ADS');
insert into user_skill (user_id, skill_definition) values (55, 'Yields');
insert into user_skill (user_id, skill_definition) values (56, 'Medical Affairs');
insert into user_skill (user_id, skill_definition) values (57, 'Business Ethics');
insert into user_skill (user_id, skill_definition) values (58, 'LWD');
insert into user_skill (user_id, skill_definition) values (59, 'PFS');
insert into user_skill (user_id, skill_definition) values (60, 'SAP EBP');
insert into user_skill (user_id, skill_definition) values (61, 'NXP');
insert into user_skill (user_id, skill_definition) values (62, 'VNA');
insert into user_skill (user_id, skill_definition) values (63, 'BSSAP');
insert into user_skill (user_id, skill_definition) values (64, 'Undercover');
insert into user_skill (user_id, skill_definition) values (65, 'NDDS');
insert into user_skill (user_id, skill_definition) values (66, 'RPG Free');
insert into user_skill (user_id, skill_definition) values (67, 'FX Swaps');
insert into user_skill (user_id, skill_definition) values (68, 'MQL4');
insert into user_skill (user_id, skill_definition) values (69, 'Medical Devices');
insert into user_skill (user_id, skill_definition) values (70, 'DPR');
insert into user_skill (user_id, skill_definition) values (71, 'Mentoring');
insert into user_skill (user_id, skill_definition) values (72, 'EIP');
insert into user_skill (user_id, skill_definition) values (73, 'CCNA');
insert into user_skill (user_id, skill_definition) values (74, 'Defect Life Cycle');
insert into user_skill (user_id, skill_definition) values (75, 'RDCS');
insert into user_skill (user_id, skill_definition) values (76, 'EHR');
insert into user_skill (user_id, skill_definition) values (77, 'PBASIC');
insert into user_skill (user_id, skill_definition) values (78, 'Amadeus GDS');
insert into user_skill (user_id, skill_definition) values (79, 'WLL');
insert into user_skill (user_id, skill_definition) values (80, 'MVC');
insert into user_skill (user_id, skill_definition) values (81, 'WWAN');
insert into user_skill (user_id, skill_definition) values (82, 'Storytelling');
insert into user_skill (user_id, skill_definition) values (83, 'Clinical Supervision');
insert into user_skill (user_id, skill_definition) values (84, 'Snooker');
insert into user_skill (user_id, skill_definition) values (85, 'Aluminum');
insert into user_skill (user_id, skill_definition) values (86, 'Estimates');
insert into user_skill (user_id, skill_definition) values (87, 'Microsoft Dynamics');
insert into user_skill (user_id, skill_definition) values (88, 'XSD');
insert into user_skill (user_id, skill_definition) values (89, 'Outdoor Advertising');
insert into user_skill (user_id, skill_definition) values (90, 'Cisco VPN');
insert into user_skill (user_id, skill_definition) values (91, 'Ultra Low Latency');
insert into user_skill (user_id, skill_definition) values (92, 'TPT');
insert into user_skill (user_id, skill_definition) values (93, 'Vulnerability Research');
insert into user_skill (user_id, skill_definition) values (94, 'TMF');
insert into user_skill (user_id, skill_definition) values (95, 'For Sale By Owner');
insert into user_skill (user_id, skill_definition) values (96, 'Statistical Data Analysis');
insert into user_skill (user_id, skill_definition) values (97, 'CEO/CFO Certification');
insert into user_skill (user_id, skill_definition) values (98, 'CFTC');
insert into user_skill (user_id, skill_definition) values (99, 'PMO Services');
insert into user_skill (user_id, skill_definition) values (100, 'Blood Typing');
insert into user_skill (user_id, skill_definition) values (1, 'DOS');
insert into user_skill (user_id, skill_definition) values (2, 'XML Sitemaps');
insert into user_skill (user_id, skill_definition) values (3, 'QIP');
insert into user_skill (user_id, skill_definition) values (4, 'JGrasp');
insert into user_skill (user_id, skill_definition) values (5, 'AFM');
insert into user_skill (user_id, skill_definition) values (6, 'USDA');
insert into user_skill (user_id, skill_definition) values (7, 'HP Openview');
insert into user_skill (user_id, skill_definition) values (8, 'Buyer Representation');
insert into user_skill (user_id, skill_definition) values (9, 'CMake');
insert into user_skill (user_id, skill_definition) values (10, 'DFLSS');
insert into user_skill (user_id, skill_definition) values (11, 'UK Immigration');
insert into user_skill (user_id, skill_definition) values (12, 'SBR');
insert into user_skill (user_id, skill_definition) values (13, 'NHS Commissioning');
insert into user_skill (user_id, skill_definition) values (14, 'UB04');
insert into user_skill (user_id, skill_definition) values (15, 'IEC 60601');
insert into user_skill (user_id, skill_definition) values (16, 'Naval Architecture');
insert into user_skill (user_id, skill_definition) values (17, 'Molecular Biology');
insert into user_skill (user_id, skill_definition) values (18, 'JMP');
insert into user_skill (user_id, skill_definition) values (19, 'Employee Management');
insert into user_skill (user_id, skill_definition) values (20, 'Amazon Web Services (AWS)');
insert into user_skill (user_id, skill_definition) values (21, 'Comic Book Illustration');
insert into user_skill (user_id, skill_definition) values (22, 'Petroleum');
insert into user_skill (user_id, skill_definition) values (23, 'Yellow Belt');
insert into user_skill (user_id, skill_definition) values (24, 'Pharmaceutical Industry');
insert into user_skill (user_id, skill_definition) values (25, 'HR Solutions');
insert into user_skill (user_id, skill_definition) values (26, 'NCP');
insert into user_skill (user_id, skill_definition) values (27, 'Administrative Law');
insert into user_skill (user_id, skill_definition) values (28, 'Hotel Booking');
insert into user_skill (user_id, skill_definition) values (29, 'cGMP manufacturing');
insert into user_skill (user_id, skill_definition) values (30, 'Eyelash &amp; Eyebrow Tinting');
insert into user_skill (user_id, skill_definition) values (31, 'Investment Banking');
insert into user_skill (user_id, skill_definition) values (32, 'Multithreading');
insert into user_skill (user_id, skill_definition) values (33, 'SAP XI');
insert into user_skill (user_id, skill_definition) values (34, 'Tomcat');
insert into user_skill (user_id, skill_definition) values (35, 'BMC Remedy User');
insert into user_skill (user_id, skill_definition) values (36, 'Sleepwear');
insert into user_skill (user_id, skill_definition) values (37, 'Jewish Studies');
insert into user_skill (user_id, skill_definition) values (38, 'ITIL Certified');
insert into user_skill (user_id, skill_definition) values (39, 'HSSE');
insert into user_skill (user_id, skill_definition) values (40, 'PFlow');
insert into user_skill (user_id, skill_definition) values (41, 'PDI');
insert into user_skill (user_id, skill_definition) values (42, 'QlikView');
insert into user_skill (user_id, skill_definition) values (43, 'European Studies');
insert into user_skill (user_id, skill_definition) values (44, 'Gnuplot');
insert into user_skill (user_id, skill_definition) values (45, 'BPF');
insert into user_skill (user_id, skill_definition) values (46, 'Military Logistics');
insert into user_skill (user_id, skill_definition) values (47, 'IATSE');
insert into user_skill (user_id, skill_definition) values (48, 'XBR');
insert into user_skill (user_id, skill_definition) values (49, 'MRI Plus');
insert into user_skill (user_id, skill_definition) values (50, 'Testing Types');
insert into user_skill (user_id, skill_definition) values (51, 'Ultimate Frisbee');
insert into user_skill (user_id, skill_definition) values (52, 'Online Marketing');
insert into user_skill (user_id, skill_definition) values (53, 'Kickboxing');
insert into user_skill (user_id, skill_definition) values (54, 'Windows Azure');
insert into user_skill (user_id, skill_definition) values (55, 'MRP');
insert into user_skill (user_id, skill_definition) values (56, 'XBRL');
insert into user_skill (user_id, skill_definition) values (57, 'RMIS');
insert into user_skill (user_id, skill_definition) values (58, 'GFAS');
insert into user_skill (user_id, skill_definition) values (59, 'Management Consulting');
insert into user_skill (user_id, skill_definition) values (60, 'LSO');
insert into user_skill (user_id, skill_definition) values (61, 'Key Account Development');
insert into user_skill (user_id, skill_definition) values (62, 'SQL Server Management Studio');
insert into user_skill (user_id, skill_definition) values (63, 'Aquatic Ecology');
insert into user_skill (user_id, skill_definition) values (64, 'Style Guides');
insert into user_skill (user_id, skill_definition) values (65, 'HDPE');
insert into user_skill (user_id, skill_definition) values (66, 'First Year Experience');
insert into user_skill (user_id, skill_definition) values (67, 'UB04');
insert into user_skill (user_id, skill_definition) values (68, 'PMIS');
insert into user_skill (user_id, skill_definition) values (69, 'DUI Defense');
insert into user_skill (user_id, skill_definition) values (70, 'Lua');
insert into user_skill (user_id, skill_definition) values (71, 'EWB');
insert into user_skill (user_id, skill_definition) values (72, 'Yacht Clubs');
insert into user_skill (user_id, skill_definition) values (73, 'NATO');
insert into user_skill (user_id, skill_definition) values (74, 'R&amp;TTE');
insert into user_skill (user_id, skill_definition) values (75, 'Email Marketing');
insert into user_skill (user_id, skill_definition) values (76, 'MP2');
insert into user_skill (user_id, skill_definition) values (77, 'Xenix');
insert into user_skill (user_id, skill_definition) values (78, 'GSM-R');
insert into user_skill (user_id, skill_definition) values (79, 'Visual Arts');
insert into user_skill (user_id, skill_definition) values (80, 'Organizational Design');
insert into user_skill (user_id, skill_definition) values (81, 'IGMP');
insert into user_skill (user_id, skill_definition) values (82, 'Window Displays');
insert into user_skill (user_id, skill_definition) values (83, 'Access');
insert into user_skill (user_id, skill_definition) values (84, 'KMS');
insert into user_skill (user_id, skill_definition) values (85, 'JPA');
insert into user_skill (user_id, skill_definition) values (86, 'MPR');
insert into user_skill (user_id, skill_definition) values (87, 'Claims Management');
insert into user_skill (user_id, skill_definition) values (88, 'MVNE');
insert into user_skill (user_id, skill_definition) values (89, 'Ghosts');
insert into user_skill (user_id, skill_definition) values (90, 'AXE');
insert into user_skill (user_id, skill_definition) values (91, 'Hypertension');
insert into user_skill (user_id, skill_definition) values (92, 'CFII');
insert into user_skill (user_id, skill_definition) values (93, 'International Trade');
insert into user_skill (user_id, skill_definition) values (94, 'Non-linear Editing');
insert into user_skill (user_id, skill_definition) values (95, 'Industrial Ethernet');
insert into user_skill (user_id, skill_definition) values (96, 'Egyptology');
insert into user_skill (user_id, skill_definition) values (97, 'CSRs');
insert into user_skill (user_id, skill_definition) values (98, 'UK Employment Law');
insert into user_skill (user_id, skill_definition) values (99, 'MBR');
insert into user_skill (user_id, skill_definition) values (100, 'LPT');
insert into user_skill (user_id, skill_definition) values (1, 'Java Enterprise Edition');
insert into user_skill (user_id, skill_definition) values (2, 'ABS');
insert into user_skill (user_id, skill_definition) values (3, 'ADP Payroll');
insert into user_skill (user_id, skill_definition) values (4, 'Editorial');
insert into user_skill (user_id, skill_definition) values (5, 'VMS');
insert into user_skill (user_id, skill_definition) values (6, 'Nuclear');
insert into user_skill (user_id, skill_definition) values (7, 'Yarn');
insert into user_skill (user_id, skill_definition) values (8, 'Order Picking');
insert into user_skill (user_id, skill_definition) values (9, 'Whiplash');
insert into user_skill (user_id, skill_definition) values (10, 'NSF');
insert into user_skill (user_id, skill_definition) values (11, 'LDAP');
insert into user_skill (user_id, skill_definition) values (12, 'GCS');
insert into user_skill (user_id, skill_definition) values (13, 'Siding');
insert into user_skill (user_id, skill_definition) values (14, 'Zero Waste');
insert into user_skill (user_id, skill_definition) values (15, 'Green Building');
insert into user_skill (user_id, skill_definition) values (16, 'XTRACT');
insert into user_skill (user_id, skill_definition) values (17, 'FTK');
insert into user_skill (user_id, skill_definition) values (18, 'Yin Yoga');
insert into user_skill (user_id, skill_definition) values (19, 'Telephone Skills');
insert into user_skill (user_id, skill_definition) values (20, 'Web TV');
insert into user_skill (user_id, skill_definition) values (21, 'Class Actions');
insert into user_skill (user_id, skill_definition) values (22, 'FCNSP');
insert into user_skill (user_id, skill_definition) values (23, 'VLC');
insert into user_skill (user_id, skill_definition) values (24, 'Emerging Markets');
insert into user_skill (user_id, skill_definition) values (25, 'Ocular Disease');
insert into user_skill (user_id, skill_definition) values (26, 'FP7');
insert into user_skill (user_id, skill_definition) values (27, 'ICT Governance');
insert into user_skill (user_id, skill_definition) values (28, 'Runway');
insert into user_skill (user_id, skill_definition) values (29, 'DFSS Green Belt');
insert into user_skill (user_id, skill_definition) values (30, 'Luxury Travel');
insert into user_skill (user_id, skill_definition) values (31, 'Museums');
insert into user_skill (user_id, skill_definition) values (32, 'RFC');
insert into user_skill (user_id, skill_definition) values (33, 'CTM');
insert into user_skill (user_id, skill_definition) values (34, 'Yardi Enterprise');
insert into user_skill (user_id, skill_definition) values (35, 'DVD Studio Pro');
insert into user_skill (user_id, skill_definition) values (36, 'NDIS');
insert into user_skill (user_id, skill_definition) values (37, 'RQM');
insert into user_skill (user_id, skill_definition) values (38, 'Geometric Dimensioning &amp; Tolerancing');
insert into user_skill (user_id, skill_definition) values (39, 'GNSS');
insert into user_skill (user_id, skill_definition) values (40, 'GMI');
insert into user_skill (user_id, skill_definition) values (41, 'Green Belt');
insert into user_skill (user_id, skill_definition) values (42, 'Hyper-V');
insert into user_skill (user_id, skill_definition) values (43, 'LAN-WAN');
insert into user_skill (user_id, skill_definition) values (44, 'LGD');
insert into user_skill (user_id, skill_definition) values (45, 'Petroleum');
insert into user_skill (user_id, skill_definition) values (46, 'HQL');
insert into user_skill (user_id, skill_definition) values (47, 'GSM-R');
insert into user_skill (user_id, skill_definition) values (48, 'BIM');
insert into user_skill (user_id, skill_definition) values (49, 'PFEP');
insert into user_skill (user_id, skill_definition) values (50, 'Copy Typing');
insert into user_skill (user_id, skill_definition) values (51, 'Translation');
insert into user_skill (user_id, skill_definition) values (52, 'FDCPA');
insert into user_skill (user_id, skill_definition) values (53, 'Affiliate Management');
insert into user_skill (user_id, skill_definition) values (54, 'Banking');
insert into user_skill (user_id, skill_definition) values (55, 'Finite Element Analysis');
insert into user_skill (user_id, skill_definition) values (56, 'Ab Initio');
insert into user_skill (user_id, skill_definition) values (57, 'Radio Promotions');
insert into user_skill (user_id, skill_definition) values (58, 'HR Metrics');
insert into user_skill (user_id, skill_definition) values (59, 'Field Work');
insert into user_skill (user_id, skill_definition) values (60, 'Recruitment Advertising');
insert into user_skill (user_id, skill_definition) values (61, 'Managed Care');
insert into user_skill (user_id, skill_definition) values (62, 'International Real Estate');
insert into user_skill (user_id, skill_definition) values (63, 'Embedded SQL');
insert into user_skill (user_id, skill_definition) values (64, 'CPLEX');
insert into user_skill (user_id, skill_definition) values (65, 'Branding &amp; Identity');
insert into user_skill (user_id, skill_definition) values (66, 'CGL');
insert into user_skill (user_id, skill_definition) values (67, 'Crisis Communications');
insert into user_skill (user_id, skill_definition) values (68, 'Irrigation Management');
insert into user_skill (user_id, skill_definition) values (69, 'CSCS');
insert into user_skill (user_id, skill_definition) values (70, 'Electrical Engineering');
insert into user_skill (user_id, skill_definition) values (71, 'Differentiated Instruction');
insert into user_skill (user_id, skill_definition) values (72, 'PBX');
insert into user_skill (user_id, skill_definition) values (73, 'CNC Programing');
insert into user_skill (user_id, skill_definition) values (74, 'Young Adults');
insert into user_skill (user_id, skill_definition) values (75, '21 CFR Part 11');
insert into user_skill (user_id, skill_definition) values (76, 'ICP-OES');
insert into user_skill (user_id, skill_definition) values (77, 'IO');
insert into user_skill (user_id, skill_definition) values (78, 'CDPE Designation');
insert into user_skill (user_id, skill_definition) values (79, 'Youth Mentoring');
insert into user_skill (user_id, skill_definition) values (80, 'Analysis');
insert into user_skill (user_id, skill_definition) values (81, 'Steam Turbines');
insert into user_skill (user_id, skill_definition) values (82, 'JProfiler');
insert into user_skill (user_id, skill_definition) values (83, 'CBI');
insert into user_skill (user_id, skill_definition) values (84, 'EHS');
insert into user_skill (user_id, skill_definition) values (85, 'QinQ');
insert into user_skill (user_id, skill_definition) values (86, 'HR Consulting');
insert into user_skill (user_id, skill_definition) values (87, 'Culinary Skills');
insert into user_skill (user_id, skill_definition) values (88, 'QML');
insert into user_skill (user_id, skill_definition) values (89, 'Tgrid');
insert into user_skill (user_id, skill_definition) values (90, 'SFR');
insert into user_skill (user_id, skill_definition) values (91, 'OLEDB');
insert into user_skill (user_id, skill_definition) values (92, 'PCI DSS');
insert into user_skill (user_id, skill_definition) values (93, 'Novell');
insert into user_skill (user_id, skill_definition) values (94, 'FTIR');
insert into user_skill (user_id, skill_definition) values (95, 'SQL');
insert into user_skill (user_id, skill_definition) values (96, 'Krav Maga');
insert into user_skill (user_id, skill_definition) values (97, 'Offshore Operations');
insert into user_skill (user_id, skill_definition) values (98, 'Brand Ambassadorship');
insert into user_skill (user_id, skill_definition) values (99, 'CATIA');
insert into user_skill (user_id, skill_definition) values (100, 'Ethernet over Copper');