insert into user_accomplishment (user_id, accomplishment_definition) values (1, 'Wastewater Treatment');
insert into user_accomplishment (user_id, accomplishment_definition) values (2, 'SMSTS');
insert into user_accomplishment (user_id, accomplishment_definition) values (3, 'DNV');
insert into user_accomplishment (user_id, accomplishment_definition) values (4, 'SFX Editing');
insert into user_accomplishment (user_id, accomplishment_definition) values (5, 'Electronic Trading');
insert into user_accomplishment (user_id, accomplishment_definition) values (6, 'Nintex');
insert into user_accomplishment (user_id, accomplishment_definition) values (7, 'European Politics');
insert into user_accomplishment (user_id, accomplishment_definition) values (8, 'First Time Home Buyers');
insert into user_accomplishment (user_id, accomplishment_definition) values (9, 'Fitness');
insert into user_accomplishment (user_id, accomplishment_definition) values (10, 'Erwin');
insert into user_accomplishment (user_id, accomplishment_definition) values (11, 'IMS DB/DC');
insert into user_accomplishment (user_id, accomplishment_definition) values (12, 'PDMS Design');
insert into user_accomplishment (user_id, accomplishment_definition) values (13, 'Fashion');
insert into user_accomplishment (user_id, accomplishment_definition) values (14, 'Hedge Funds');
insert into user_accomplishment (user_id, accomplishment_definition) values (15, 'Musical Theatre');
insert into user_accomplishment (user_id, accomplishment_definition) values (16, 'User Research');
insert into user_accomplishment (user_id, accomplishment_definition) values (17, 'Alarm Systems');
insert into user_accomplishment (user_id, accomplishment_definition) values (18, 'Eclipse RCP');
insert into user_accomplishment (user_id, accomplishment_definition) values (19, 'OSHA 10-Hour');
insert into user_accomplishment (user_id, accomplishment_definition) values (20, 'DHTMLX');
insert into user_accomplishment (user_id, accomplishment_definition) values (21, 'Infor XA');
insert into user_accomplishment (user_id, accomplishment_definition) values (22, 'LLBLGen');
insert into user_accomplishment (user_id, accomplishment_definition) values (23, 'Biomass');
insert into user_accomplishment (user_id, accomplishment_definition) values (24, 'Credit Analysis');
insert into user_accomplishment (user_id, accomplishment_definition) values (25, 'RSL');
insert into user_accomplishment (user_id, accomplishment_definition) values (26, 'Conservation Issues');
insert into user_accomplishment (user_id, accomplishment_definition) values (27, 'DNS Administration');
insert into user_accomplishment (user_id, accomplishment_definition) values (28, 'CTF');
insert into user_accomplishment (user_id, accomplishment_definition) values (29, 'QSIG');
insert into user_accomplishment (user_id, accomplishment_definition) values (30, 'Kitchen Cabinets');
insert into user_accomplishment (user_id, accomplishment_definition) values (31, 'AV Integration');
insert into user_accomplishment (user_id, accomplishment_definition) values (32, 'Mathematical Modeling');
insert into user_accomplishment (user_id, accomplishment_definition) values (33, 'RCFA');
insert into user_accomplishment (user_id, accomplishment_definition) values (34, 'IGRP');
insert into user_accomplishment (user_id, accomplishment_definition) values (35, 'HEC-HMS');
insert into user_accomplishment (user_id, accomplishment_definition) values (36, 'DDR3');
insert into user_accomplishment (user_id, accomplishment_definition) values (37, 'IFS');
insert into user_accomplishment (user_id, accomplishment_definition) values (38, 'eGain');
insert into user_accomplishment (user_id, accomplishment_definition) values (39, 'Big 4');
insert into user_accomplishment (user_id, accomplishment_definition) values (40, 'MPLS VPN');
insert into user_accomplishment (user_id, accomplishment_definition) values (41, 'Family Law');
insert into user_accomplishment (user_id, accomplishment_definition) values (42, 'Aspen HYSYS');
insert into user_accomplishment (user_id, accomplishment_definition) values (43, 'MX960');
insert into user_accomplishment (user_id, accomplishment_definition) values (44, 'GIS Modeling');
insert into user_accomplishment (user_id, accomplishment_definition) values (45, 'Avid DS Nitris');
insert into user_accomplishment (user_id, accomplishment_definition) values (46, 'XML Sitemaps');
insert into user_accomplishment (user_id, accomplishment_definition) values (47, 'eBusiness Suite');
insert into user_accomplishment (user_id, accomplishment_definition) values (48, 'Horticulture');
insert into user_accomplishment (user_id, accomplishment_definition) values (49, 'Platform LSF');
insert into user_accomplishment (user_id, accomplishment_definition) values (50, 'Compensation &amp; Benefits');
insert into user_accomplishment (user_id, accomplishment_definition) values (51, 'HLA');
insert into user_accomplishment (user_id, accomplishment_definition) values (52, 'Telecom BSS');
insert into user_accomplishment (user_id, accomplishment_definition) values (53, 'Marketing');
insert into user_accomplishment (user_id, accomplishment_definition) values (54, 'Offshore Drilling');
insert into user_accomplishment (user_id, accomplishment_definition) values (55, 'Kundalini Yoga');
insert into user_accomplishment (user_id, accomplishment_definition) values (56, 'SSL');
insert into user_accomplishment (user_id, accomplishment_definition) values (57, 'Vehicles');
insert into user_accomplishment (user_id, accomplishment_definition) values (58, 'Slip &amp; Fall');
insert into user_accomplishment (user_id, accomplishment_definition) values (59, 'DNV');
insert into user_accomplishment (user_id, accomplishment_definition) values (60, 'Earthquake Engineering');
insert into user_accomplishment (user_id, accomplishment_definition) values (61, 'Sustainability');
insert into user_accomplishment (user_id, accomplishment_definition) values (62, 'PDL');
insert into user_accomplishment (user_id, accomplishment_definition) values (63, 'DTH');
insert into user_accomplishment (user_id, accomplishment_definition) values (64, 'External Audit');
insert into user_accomplishment (user_id, accomplishment_definition) values (65, 'SVT');
insert into user_accomplishment (user_id, accomplishment_definition) values (66, 'MS Reporting Services');
insert into user_accomplishment (user_id, accomplishment_definition) values (67, 'GPP');
insert into user_accomplishment (user_id, accomplishment_definition) values (68, 'Venue Management');
insert into user_accomplishment (user_id, accomplishment_definition) values (69, 'GNU Radio');
insert into user_accomplishment (user_id, accomplishment_definition) values (70, 'JScript');
insert into user_accomplishment (user_id, accomplishment_definition) values (71, 'Running');
insert into user_accomplishment (user_id, accomplishment_definition) values (72, 'Construction Management');
insert into user_accomplishment (user_id, accomplishment_definition) values (73, 'Quantitative Finance');
insert into user_accomplishment (user_id, accomplishment_definition) values (74, 'MXML');
insert into user_accomplishment (user_id, accomplishment_definition) values (75, 'IBM BPM');
insert into user_accomplishment (user_id, accomplishment_definition) values (76, 'AV Integration');
insert into user_accomplishment (user_id, accomplishment_definition) values (77, 'Radiology');
insert into user_accomplishment (user_id, accomplishment_definition) values (78, 'RCRA');
insert into user_accomplishment (user_id, accomplishment_definition) values (79, 'Outdoor Recreation');
insert into user_accomplishment (user_id, accomplishment_definition) values (80, 'Medication Therapy Management');
insert into user_accomplishment (user_id, accomplishment_definition) values (81, 'Hypnosis');
insert into user_accomplishment (user_id, accomplishment_definition) values (82, 'Kaspersky Antivirus');
insert into user_accomplishment (user_id, accomplishment_definition) values (83, 'HVAC Design');
insert into user_accomplishment (user_id, accomplishment_definition) values (84, 'Syslog-ng');
insert into user_accomplishment (user_id, accomplishment_definition) values (85, 'Tunneling');
insert into user_accomplishment (user_id, accomplishment_definition) values (86, 'Pre-owned');
insert into user_accomplishment (user_id, accomplishment_definition) values (87, 'Db4o');
insert into user_accomplishment (user_id, accomplishment_definition) values (88, 'QRC');
insert into user_accomplishment (user_id, accomplishment_definition) values (89, 'HTML Emails');
insert into user_accomplishment (user_id, accomplishment_definition) values (90, 'Rural Development');
insert into user_accomplishment (user_id, accomplishment_definition) values (91, 'PNR');
insert into user_accomplishment (user_id, accomplishment_definition) values (92, 'Youth Ministry');
insert into user_accomplishment (user_id, accomplishment_definition) values (93, 'Requirements Analysis');
insert into user_accomplishment (user_id, accomplishment_definition) values (94, 'XP/Vista/7');
insert into user_accomplishment (user_id, accomplishment_definition) values (95, 'Programming');
insert into user_accomplishment (user_id, accomplishment_definition) values (96, 'MDOP');
insert into user_accomplishment (user_id, accomplishment_definition) values (97, 'E-on Vue');
insert into user_accomplishment (user_id, accomplishment_definition) values (98, 'Slope Stability');
insert into user_accomplishment (user_id, accomplishment_definition) values (99, 'Ektron');
insert into user_accomplishment (user_id, accomplishment_definition) values (100, 'MDB');